name: json_utils
description: Dart utilities for JSON serialisation & deserialisation.
version: 0.0.0-a1

environment:
  sdk: '>=3.0.1 <4.0.0'

dev_dependencies:
  enspyr_lints: ^0.0.0-a1
  test: ^1.24.3
